[package]
name = "verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
# from template
methods = { path = "../methods" }
risc0-zkvm = { version = "0.19.1" }
env_logger = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
