name: Docker Build Guest

on:
  push:
    branches: [ verifier ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  # , self-hosted
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker guest image (manual)
      run: |
        cargo risczero build --manifest-path ./methods/guest/Cargo.toml

      
        


       

    - name: Build and Push Docker image with custom tag
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: e36io/hyperfridge-r0-guest:${{ env.IMAGE_TAG }}

    - name: Create GitHub Tag
      if: github.event_name != 'pull_request'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ env.IMAGE_TAG }}
        git push origin ${{ env.IMAGE_TAG }}        
