name: Docker Build MacOs

on:
  push:
    branches: [ macos ]

jobs:
  build:
    runs-on: macos-latest  # , l5, self-hosted
    permissions:
      contents: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    -
      name: Set up Docker
      uses: crazy-max/ghaction-setup-docker@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image (manual)
      run: |
        docker buildx build -f DockerfileMacOs --load -t test .
  
  